- name: Create a highly available K3s cluster with Kube-VIP, Keepalived, and HAProxy
  hosts: masters
  become: yes
  vars:
    k3s_version: "v1.22.7+k3s1"
    #vip: "192.168.1.20"
    #vip_interface: "ens160"
    #haproxy_ip: "192.168.1.30"  # IP address of HAProxy node
    #metallb_address_range:
    #  - "192.168.1.100-192.168.1.120"
    k3s_token: "alphasapphireandomegaruby"

  tasks:
    - name: Ensure required packages are installed
      package:
        name: "{{ item }}"
        state: present
      loop:
        - curl

    - name: Install K3s on first master node
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_TOKEN={{ k3s_token }} sh -
      when: inventory_hostname == groups['masters'][0]

    - name: Install k3s on worker nodes
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_URL=https://['masters'][0]:6443 K3S_TOKEN={{ token }} sh -
      when: "'workers' in group_names"
