---
- hosts: master
  become: yes
  vars:
    k3s_version: "v1.30.0+k3s1"
    metallb_version: "v0.13.10"
    metallb_ip_range: "192.168.1.100-192.168.1.110"  # Adjust this range based on your network
    
  tasks:
    - name: Install K3s on master
      shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Get K3s token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: get token for workers
      set_fact: 
          k3s_token: "{{ k3s_token.stdout }}"

### NEW ###

    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Add MetalLB Helm repo
      shell: helm repo add metallb https://metallb.github.io/metallb

    - name: Update Helm repos
      shell: helm repo update    

    - name: Create MetalLB namespace
      shell: kubectl create namespace metallb-system || true

    - name: Install MetalLB
      shell: helm install metallb metallb/metallb --namespace metallb-system --version {{ metallb_version }}
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Configure MetalLB
      copy:
        dest: /tmp/metallb-config.yaml
        content: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            namespace: metallb-system
            name: config
          data:
            config: |
              address-pools:
              - name: default
                protocol: layer2
                addresses:
                - {{ metallb_ip_range }}

    - name: Apply MetalLB configuration
      shell: kubectl apply -f /tmp/metallb-config.yaml
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
### NEW ###

- hosts: workers
  become: yes
  vars:
    k3s_version: "v1.30.0+k3s1"
  tasks:
    - name: Install K3s agent
      shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_URL=https://{{ group['master'][0] }}:6443 K3S_TOKEN={{ hostvars[groups['master'][0]].k3s_token }} sh -
      args:
        creates: /usr/local/bin/k3s-agent
